services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DivineOmega\PasswordExposed\Interfaces\PasswordExposedCheckerInterface: '@DivineOmega\PasswordExposed\PasswordExposedChecker'
    DivineOmega\PasswordExposed\PasswordExposedChecker: ~

    DivineOmega\PasswordExposed\Symfony\Validator\Constraints\PasswordExposedValidator: ~
