services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $enable: '%password_exposed.enable%'

    DivineOmega\PasswordExposed\Interfaces\PasswordExposedCheckerInterface: '@DivineOmega\PasswordExposed\PasswordExposedChecker'
    DivineOmega\PasswordExposed\PasswordExposedChecker: ~

    DivineOmega\PasswordExposed\Symfony\Validator\Constraints\PasswordExposedValidator: ~
